name: LLMOps CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run basic application test
      # This is a simple test to ensure the app can start and dependencies are met.
      # For a real project, you'd add unit tests for app.py logic.
      run: |
        echo "Attempting to import Flask and google.generativeai..."
        python -c "import flask; import google.generativeai; print('Imports successful!')"
        echo "Basic application check passed."

    # Optional: Add linting, more comprehensive tests here ##
